fullnameOverride: gateway-service

image:
  repository: "gateway-service"
  pullPolicy: "IfNotPresent"
  
service:
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: ""
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: gateway-service
              port:
                number: 8080
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gateway-service
              port:
                number: 8080

livenessProbe:
  httpGet:
    path: /manage/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /manage/health
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3