fullnameOverride: statistics-service

image:
  repository: ""
  tag: "latest"

service:
  port: 8100

env:
  - name: DOCKER_CONNECT_STRING
    value: "Host=postgres;Port=5432;Database=statistics;Username=postgres;Password=postgres"
  - name: Kafka__BootstrapServers
    value: "http://kafka:9092"

livenessProbe:
  httpGet:
    path: /manage/health
    port: 8100
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /manage/health
    port: 8100
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3