<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-IdentityService-e9f8f9ce-e365-4ad0-9d7d-dd0525e0d1df</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.26" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.13">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
        <PackageReference Include="OpenIddict.Abstractions" Version="7.5.0" />
        <PackageReference Include="OpenIddict.AspNetCore" Version="7.5.0" />
        <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="7.5.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    </ItemGroup>
    
    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Common\Common.csproj" />
    </ItemGroup>
</Project>
