version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    networks:
      - flight-booking-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  flight-service:
    build:
      context: .
      dockerfile: services/FlightService/Dockerfile
    container_name: flight-service
    environment:
      - DOCKER_CONNECT_STRING=Host=postgres;Port=5432;Database=flights;Username=postgres;Password=postgres
      - ASPNETCORE_HTTP_PORTS=8060
    ports:
      - "8060:8060"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - flight-booking-network

  tickets-service:
    build:
      context: .
      dockerfile: services/TicketsService/Dockerfile
    container_name: tickets-service
    environment:
      - DOCKER_CONNECT_STRING=Host=postgres;Port=5432;Database=tickets;Username=postgres;Password=postgres
      - ASPNETCORE_HTTP_PORTS=8070
    ports:
      - "8070:8070"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - flight-booking-network

  bonus-service:
    build:
      context: .
      dockerfile: services/BonusService/Dockerfile
    container_name: bonus-service
    environment:
      - DOCKER_CONNECT_STRING=Host=postgres;Port=5432;Database=privileges;Username=postgres;Password=postgres
      - ASPNETCORE_HTTP_PORTS=8050
    ports:
      - "8050:8050"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - flight-booking-network

  gateway-service:
    build:
      context: .
      dockerfile: services/GatewayService/Dockerfile
    container_name: gateway-service
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - flight-booking-network

volumes:
  postgres_data:

networks:
  flight-booking-network:
    driver: bridge