apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: test
data:
  01-init.sql: |
    CREATE TABLE IF NOT EXISTS flights
    CREATE TABLE IF NOT EXISTS tickets
    CREATE TABLE IF NOT EXISTS bonuses