replicaCount: 2

image:
  registry: ghcr.io
  repository: benc-uk/keycloak
  tag: latest

keycloak:
  httpPort: 7000
  clustered: true
  proxyMode: edge
  adminUser: admin
  healthCheckPath: /auth/realms/master
  hostnamePath: auth
  
database:
  passwordSecret:
    name: postgres
    key: postgres
  username: "postgres"
  host: "postgres"
  databaseName: "keycloak-postgres"

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: keycloak.example.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: false
    hosts:
      - keycloak.example.net
    secretName: benco-io-cert
    
command:
  - "/opt/keycloak/bin/kc.sh"
args:
  - "start-dev"