ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: keycloak.example.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - keycloak.example.net
      secretName: benco-io-cert