ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: keycloak.example.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: false
    hosts:
      - keycloak.example.net
    secretName: benco-io-cert
    
command:
  - "/opt/keycloak/bin/kc.sh"
args:
  - "start-dev"